- name: Copy website tarball to server
  copy:
    src: /var/www/website.tar.gz        # Path to the tarball on your local machine
    dest: /tmp/website.tar.gz           # Temporary location on the server

- name: Extract website tarball
  unarchive:
    src: /tmp/website.tar.gz            # Path to the tarball on the remote server
    dest: /var/www/html                 # Extract to the web server’s root directory
    remote_src: yes

- name: Set permissions for website files
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

